# GitHub Issue Labels Configuration
# These labels help organize and categorize issues and PRs

# Type labels
- name: "bug"
  color: "d73a4a"
  description: "Something isn't working"

- name: "enhancement"
  color: "a2eeef"
  description: "New feature or request"

- name: "documentation"
  color: "0075ca"
  description: "Improvements or additions to documentation"

- name: "question"
  color: "d876e3"
  description: "Further information is requested"

# Priority labels
- name: "priority: critical"
  color: "b60205"
  description: "Critical issue requiring immediate attention"

- name: "priority: high"
  color: "ff9800"
  description: "High priority issue"

- name: "priority: medium"
  color: "fbca04"
  description: "Medium priority issue"

- name: "priority: low"
  color: "0e8a16"
  description: "Low priority issue"

# Status labels
- name: "status: in progress"
  color: "yellow"
  description: "Work is in progress"

- name: "status: blocked"
  color: "red"
  description: "Blocked by another issue or external dependency"

- name: "status: needs review"
  color: "blueviolet"
  description: "Waiting for code review"

- name: "status: needs info"
  color: "d876e3"
  description: "More information needed from reporter"

# Component labels
- name: "area: authentication"
  color: "c2e0c6"
  description: "OAuth, MSAL, token management"

- name: "area: api"
  color: "c2e0c6"
  description: "Project Online or Smartsheet API integration"

- name: "area: transformation"
  color: "c2e0c6"
  description: "Data mapping and transformation logic"

- name: "area: cli"
  color: "c2e0c6"
  description: "Command-line interface"

- name: "area: templates"
  color: "c2e0c6"
  description: "Template workspace functionality"

- name: "area: testing"
  color: "c2e0c6"
  description: "Test infrastructure"

# Special labels
- name: "good first issue"
  color: "7057ff"
  description: "Good for newcomers"

- name: "help wanted"
  color: "008672"
  description: "Extra attention is needed"

- name: "duplicate"
  color: "cfd3d7"
  description: "This issue or pull request already exists"

- name: "wontfix"
  color: "ffffff"
  description: "This will not be worked on"

- name: "dependencies"
  color: "0366d6"
  description: "Pull requests that update a dependency file"

- name: "automated"
  color: "ededed"
  description: "Automated changes (Dependabot, etc.)"

- name: "breaking change"
  color: "b60205"
  description: "Introduces breaking changes to API or CLI"

- name: "needs tests"
  color: "fbca04"
  description: "Requires test coverage"

# Platform-specific
- name: "platform: windows"
  color: "bfd4f2"
  description: "Windows-specific issue"

- name: "platform: macos"
  color: "bfd4f2"
  description: "macOS-specific issue"

- name: "platform: linux"
  color: "bfd4f2"
  description: "Linux-specific issue"
